### ISSUE TITLE
Doesn't automatically capture metrics

### ISSUE THREAD

**Issue by skosch** [deadtrickster/prometheus_process_collector#1]
@deadtrickster, this is probably the coolest underappreciated collection of Elixir packages I've come across so far. Super awesome, thanks a million!

Unfortunately, this particular one doesn't work for me out of the box – neither in the example app, nor in my own project. All other metrics are shown beautifully, and `:prometheus_process_collector` is loaded as a module, but I can't seem to get access to my system info. Could you help me figure this out?

**Comment by deadtrickster** [comment]
Hello Sebastian!

Thank you for the kind words. The reason why it might not work for you is rather impressive (for me at least). BEAM (the Erlang VM) can run in two modes:
- interactive, when modules are loaded on demand;
- embedded, when modules are loaded at app startup.

Collectors auto-discovery mechanics can't work properly in interactive mode. However, releases are always running in embedded mode and process collector can be registered automatically. Personally I don't care much about that, but if you do, you can place something like `prometheus_process_collector:module_info()` somewhere to force module loading even in interactive mode.

**Comment by skosch** [comment]
Thanks so much! That would indeed explain it. Unfortunately, by the time I manually load the collector, even during app startup, it's too late for prometheus.erl to even notice.

What I have now found works is if I run

``` elixir
Prometheus.Registry.register_collector(:prometheus_process_collector)
```

during app startup. Do you see any downsides to this approach, or is that reliable?

**Comment by deadtrickster** [comment]
You know, you've done it absolutely right! I should've suggested you that in the first place :-). I'll add it to the docs right now.

**Comment by skosch** [comment]
Whooo :) Thank you Ilya.
