### ISSUE TITLE
Compiling problems on elixir:1.9.1-alpine docker image

### ISSUE THREAD

**Issue by saadbinakhlaq** [deadtrickster/prometheus_process_collector#20]
Cannot compile the dependency

**System:**
docker elixir:1.9.1-alpine docker image
```
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe]

Interactive Elixir (1.9.1) - press Ctrl+C to exit (type h() ENTER for help)
```

**Output**
```
server_1  | ===> Compiling prometheus_process_collector
server_1  | make: Entering directory '/app/deps/prometheus_process_collector/c_src'
server_1  | g++ -O3 -finline-functions -fPIC -I /usr/local/lib/erlang/erts-10.4.4/include/ -I /usr/local/lib/erlang/lib/erl_interface-3.12/include -std=c++11 -Wall  -c -o prometheus_process_info_linux.o prometheus_process_info_linux.cc
server_1  | cc prometheus_process_collector_nif.o prometheus_process_info_linux.o -shared -L /usr/local/lib/erlang/lib/erl_interface-3.12/lib -lerl_interface -lei -lstdc++ -o /app/deps/prometheus_process_collector/c_src/../priv/prometheus_process_collector.so
server_1  | prometheus_process_collector_nif.o: file not recognized: file format not recognized
server_1  | collect2: error: ld returned 1 exit status
server_1  | make: *** [Makefile:66: /app/deps/prometheus_process_collector/c_src/../priv/prometheus_process_collector.so] Error 1
server_1  | make: Leaving directory '/app/deps/prometheus_process_collector/c_src'
server_1  | ===> Hook for compile failed!
server_1  |
server_1  | ==> metric_service
server_1  | ** (Mix) Could not compile dependency :prometheus_process_collector, "/root/.mix/rebar3 bare compile --paths="/app/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile prometheus_process_collector", update it with "mix deps.update prometheus_process_collector" or clean it with "mix deps.clean prometheus_process_collector"
```

This works completely fine on my macOS and I can see the metrics, but when running on docker it is not compiling.

**Comment by kafaichoi** [comment]
@saadbinakhlaq sorry. I am having this issue. May I ask you if you found a way to solve it or know the reason causing it?

**Comment by saadbinakhlaq** [comment]
@bruteforcecat this was happening long time back so I dont even remember how it was fixed but I guess I had to uninstall docker and then install docker again for this to work

**Comment by kafaichoi** [comment]
Thanks for answering me @saadbinakhlaq. But I think I found the reason. To it's caused by I copying the deps from my host(macOS) to the docker container. And this include `priv/prometheus_process_collector.o` and this obviously cause the problem as the object file built in macOS is not compatible with the on in linux.

**Comment by saadbinakhlaq** [comment]
@bruteforcecat thanks that explains

**Comment by thiagosalles** [comment]
> Thanks for answering me @saadbinakhlaq. But I think I found the reason. To it's caused by I copying the deps from my host(macOS) to the docker container. And this include `priv/prometheus_process_collector.o` and this obviously cause the problem as the object file built in macOS is not compatible with the on in linux.

Thanks for sharing! That was also the problem here.
I created the .dockerignore file and put the following to avoid copying the files causing the issue and other unused files:
```
.git
_build/
deps/
priv/
```
