### ISSUE TITLE
module :prometheus_process_collector is not available

### ISSUE THREAD

**Issue by hopewise** [deadtrickster/prometheus_process_collector#4]
I also tried to use elixir official image, which is based on Debian:

> PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
> NAME="Debian GNU/Linux"
> VERSION_ID="8"
> VERSION="8 (jessie)"
> ID=debian
> HOME_URL="http://www.debian.org/"
> SUPPORT_URL="http://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"

but also, I got that error:
   >  (UndefinedFunctionError) function :prometheus_process_collector.collect_mf/2 is undefined (module :prometheus_process_collector is not available)

**Comment by deadtrickster** [comment]
I believe we figured this out on ElixirForum.
 For the history: process collector should be added to  dependencies and registered via `prometheus_registry:register_collector` or `Prometheus.Registry.register_collector`.

**Comment by hopewise** [comment]
Yes, I already did so like on ElixirForum as:
    Prometheus.Registry.register_collector(:prometheus_process_collector)
 but I got the error above, is this library supported on debian? what OS was it tested on?

**Comment by deadtrickster** [comment]
Ubuntu it should really work on any Linux. can you show your mix,exs?

**Comment by hopewise** [comment]
Here it is:

```
defmodule Trackware.Mixfile do
  use Mix.Project

  def project do
    [app: :trackware,
     version: "0.0.1",
     elixir: "~> 1.0",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix, :gettext] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     aliases: aliases,
     deps: deps]
  end

  # Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [mod: {Trackware, []},
     applications: [:phoenix, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :postgrex, :ex_aws, :httpoison, :phoenix_pubsub, :joken, :httpoison, :cqex, :exrm, :edeliver,
                    :prometheus_ex, :prometheus_ecto, :prometheus_phoenix, :prometheus_plugs, :prometheus_process_collector]]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [{:phoenix, "~> 1.2.0"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0-rc"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.9"},
     {:cowboy, "~> 1.0"},
     {:ex_aws, "~> 0.4.10"},
     {:poison, "~> 1.2"},
     {:httpoison, "~> 0.9.0"},
     {:joken, "~> 1.2"},
     {:edeliver, "~> 1.4.0"},
     {:exrm, "~> 1.0.3"},
     {:cqex, "~> 0.2.0"},
     {:cqerl, github: "matehat/cqerl"},
     {:uuid, "~> 1.1", override: true},
     {:prometheus_ex, "~> 1.0"},
     {:prometheus_ecto, "~> 1.0"},
     {:prometheus_phoenix, "~> 1.0"},
     {:prometheus_plugs, "~> 1.0"},
     {:prometheus_process_collector, "~> 1.0"},
     {:remote_monitor, "~> 0.1.0", only: :dev}]
  end

  # Aliases are shortcut or tasks specific to the current project.
  # For example, to create, migrate and run the seeds file at once:
  #
  #     $ mix ecto.setup
  #
  # See the documentation for `Mix` for more info on aliases.
  defp aliases do
    ["ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
     "ecto.reset": ["ecto.drop", "ecto.setup"]]
  end
end

```

**Comment by deadtrickster** [comment]
So you have `prometheus_process_collector` in deps and applications... and it's still not loaded? Something really strange happends (OS-independent btw).
- what's in your `_build/dev/lib/`? It should have prometheus_process_collector directory with symlinks;
- your versions are a little bit outdated. Checkout the latest here: https://hex.pm/packages?search=prometheus&sort=downloads.

**Comment by hopewise** [comment]
here is what in my r _build/dev/lib/

> > ➜  prometheus_process_collector git:(master) ✗ pwd
> > /Users/samir/Documents/projects/elixir/_build/dev/lib/prometheus_process_collector
> > 
> > ➜  prometheus_process_collector git:(master) ✗ ls
> > ebin             mix.rebar.config

I will update deps, thanks
